name: Deploy Dynamic Site Infrastructure

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'infra/01-ecs-dynamic-site/**/*.tf'
      - 'infra/01-ecs-dynamic-site/**/*.tfvars'
      - 'infra/modules/vpc/**'
      - 'infra/modules/ecr/**'
      - 'infra/modules/ecs/**'
      - 'infra/modules/dns-subdomain/**'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Deploy to dev environment when pushing to dev branch
      - name: Deploy ECS dynamic site infrastructure (dev)
        if: github.ref == 'refs/heads/dev'
        working-directory: infra/01-ecs-dynamic-site/environments/dev
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          
      
      # Deploy to prod environment when pushing to main branch
      - name: Deploy ECS dynamic site infrastructure (prod)
        if: github.ref == 'refs/heads/main'
        working-directory: infra/01-ecs-dynamic-site/environments/prod
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
